### ISSUE TITLE
Chrome is only working browser because of link rel="import"

### ISSUE THREAD

**Issue by sheibeck** [sheibeck/fatecharactersheet#8]
<link rel="import"> is not supported by a lot of the other browsers. We need another way to load the the head.htm file. There is no server-side architecture here, just pure JS/HTML, so we'll need a different way to load shared resources so we don't have to add them into every single file.

**Comment by iirelu** [comment]
Also note that even in Chrome the feature is [deprecated](https://www.chromestatus.com/feature/5144752345317376) and will be removed in a few months, rendering this site unusable in *any* browser.

**Comment by sheibeck** [comment]
Thanks for the heads up. I didn't know that.

**Comment by sheibeck** [comment]
new architecture fixes this.
